object Versions {
    const val kotlin = "1.8.20"
    const val core_ktx = "1.8.0"
    const val material = "1.7.0"
    const val constraint_layout = "2.1.4"
    const val activity_ktx = "1.5.1"
    const val fragment_ktx = "1.5.2"
    const val appcompat = "1.5.1"
    const val hilt = "2.46"
    const val lifecycle = "2.5.1"
    const val recyclerview = "1.2.1"
    const val room = "2.5.2"
    const val glide = "4.12.0"
    const val retrofit = "2.9.0"
    const val retrofit_serialization_converter = "1.0.0"
    const val retrofit_logging_interceptor = "4.11.0"
    const val timber = "5.0.1"
    const val swiperefreshlayout = "1.1.0"
    const val javax_inject = "1"
    const val coroutine_core = "1.6.3"
    const val coroutine_android = "1.6.3"
    const val junit = "4.13.2"
    const val ext_junit = "1.1.4"
    const val espresso_core = "3.5.0"
    const val kotlinx_serialization_json = "1.4.1"
    const val kotlin_serialization = "1.6.10"
    const val paging3 = "3.1.1"
}